In [1]:
from fastai.vision.all import *

In [2]:
l_compre = [x*2 for x in range(30) if x % 2 != 0]
l_compre

[2, 6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58]

Create a 3x3 tensor or array containing the numbers from 1 to 9. Double it. Select the bottom right 4 numbers

In [3]:
three_tensor = tensor([x+1 for x in range (9)])
three_tensor

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
three_tensor = three_tensor.reshape(3,3)
three_tensor


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [16]:
three_tensor = three_tensor * 2

In [18]:
three_tensor

tensor([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])

In [17]:
three_tensor[1:, 1:]

tensor([[10, 12],
        [16, 18]])